### ISSUE TITLE
If you search with google, some links redirect you to the actual link instead of rewriting it

### ISSUE THREAD

**Issue by astralevolution** [NebulaServices/Dynamic#12]
https://github.com/NebulaServices/Dynamic/assets/120140754/1f5e9985-37dc-4eef-92b7-517429795215

This page is using dynamic

**Comment by localuser-isback** [comment]
This is an issue thats not just within google, going to the network tab you can see this happens for ALOT of sites and if i have the time ill experement and see if i can find out why or whats causing it.

**Comment by astralevolution** [comment]
k

**Comment by astralevolution** [comment]
seems to be fixed in 0.7.2

**Comment by GreenyDEV** [comment]
Hi! Yeah we looked into this and the issue appears to be fixed.
