### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by justDarian** [NebulaServices/Dynamic#40]
Ive been getting discord.com, and some other people on sites like google, and youtube.

**Comment by FoxMoss** [comment]
Can you explain more about what happened? What browser are you using? Was it a specific page?

**Comment by localuser-isback** [comment]
Yeah ive had this bug happen before it tries to read the page as JSON not sure when or why it happens but its weird.

**Comment by FoxMoss** [comment]
If you encounter it again please say what browser you're using + the request payload that made it happen.

**Comment by localuser-isback** [comment]
So far its only happened to me on chromeOS with the chrome browser so i wont be able to get the request payload but sylv just said on discord "bare server failed to reach" which is mat be untrue since sometimes it starts working again or just does it once

**Comment by cohenerickson** [comment]
This is due to your bare server being unreachable, it likely originates from bare-client being unable to parse the server meta data.

**Comment by FoxMoss** [comment]
mhm so get good

**Comment by plastics-eater** [comment]
also encountered this issue, does anyone have any solutions?

**Comment by Notplayingallday383** [comment]
Swap bare servers

**Comment by justDarian** [comment]
> also encountered this issue, does anyone have any solutions?

its the bare server, either change it, reconfigure, or see any issues with networking, like ports
