### ISSUE TITLE
links within proxified websites do not work

### ISSUE THREAD

**Issue by DerpmanDev** [NebulaServices/Dynamic#47]
for example if you proxy discord.com and click login, it does not proxy it. it just does /service/login. its like that for every site and that causes alot of issues cuz some sites need to load scripts and it wouldnt work

**Comment by Riftriot** [comment]
Anything specific to recreate this? It works fine for me. Are you running in an iframe?

**Comment by DerpmanDev** [comment]
no running locally

**Comment by Riftriot** [comment]
Huh?

**Comment by DerpmanDev** [comment]
> Huh?

nvm about this issue i just messed up srry basically it was supposed to import the dist folder from esbuild but i just copied that and put it in static which causes the issue
