### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by OctoLinkYT** [NebulaServices/Dynamic#56]
1. Comma instead of period in a code block for method 1 of installation.
2. Examples url does not link to anything.

**Comment by FoxMoss** [comment]
known

**Comment by OctoLinkYT** [comment]
Ok, are you gonna fix it?

**Comment by FoxMoss** [comment]
I'm not a maintainer, I'm not here to do house keeping. Sorry about the inactivity, the project's mostly stale without active maintainers leading the direction.

**Comment by OctoLinkYT** [comment]
oh, really?

That's sad, this is the best proxy i've ever seen :(

I'll close this now.
