### ISSUE TITLE
How do i use a sock5 or http proxy?

### ISSUE THREAD

**Issue by akwin1234** [NebulaServices/Dynamic#69]
This project is awesome. I find it better than other web proxies. Amazing.

How do i use a sock5 or http proxy?
format: sock5://user:password@ip:port
or any format supporting socks5, id pass and ip, port

**Comment by FoxMoss** [comment]
This is unrelated to Dynamic. Its built for the bare server spec see https://github.com/tomphttp/specifications as apposed to a traditional http or socks5 proxy though new projects are starting to adopt https://github.com/MercuryWorkshop/wisp-protocol which is competitive with socks5.

**Comment by IncognitoTGT** [comment]
https://github.com/nebulaservices/ultraviolet also works
